### ISSUE TITLE
Errors that occur when changing styles and images

### ISSUE THREAD

**Issue by Domiantor** [EndyWon/MicroAST#8]
F:\MicroAST-main>python test_microAST.py --content inputs/content/1.jpg --style inputs/style/shuimo2.jpg
Traceback (most recent call last):
  File "test_microAST.py", line 120, in <module>
    output = network(content, style, args.alpha)
  File "D:\python3.7\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\MicroAST-main\net_microAST.py", line 317, in forward
    style_feats = self.style_encoder(style)
  File "D:\python3.7\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\MicroAST-main\net_microAST.py", line 64, in forward
    x1 = self.enc1(x)
  File "D:\python3.7\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\python3.7\lib\site-packages\torch\nn\modules\container.py", line 204, in forward
    input = module(input)
  File "D:\python3.7\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\MicroAST-main\net_microAST.py", line 18, in forward
    x = self.conv_layer(x)
  File "D:\python3.7\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\python3.7\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "D:\python3.7\lib\site-packages\torch\nn\modules\conv.py", line 460, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [16, 3, 9, 9], expected input[1, 4, 775, 511] to have 3 channels, but got 4 channels instead

**Comment by Domiantor** [comment]
It's already worked out. Just turn the picture into three channels
